
# 20260128 - RTM2D input
eval_key: 'validate'
root_dir: "/Volumes/Z/mesh_compare/"

GT_file_pitch_correct:  '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/GT3D/VEHS_6D_downsample5_keep1_37_v2_pitch_correct_modified_RTM2D.pkl'  # (267300, 37, 3)
GT_file:  '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/GT3D/VEHS_6D_downsample5_keep1_37_v2_modified_RTM2D.pkl'  # (267300, 37, 3)
GT_6D_name_list: ['PELVIS', 'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT', 'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER', 'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS', 'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

## MB 17 kpts
estimate_3D_name_list: ['HIP_c', 'RHIP', 'RKNEE', 'RANKLE', 'LHIP', 'LKNEE', 'LANKLE', 'T8', 'H36M_THORAX', 'H36M_NECK', 'H36M_HEAD', 'LSHOULDER', 'LELBOW', 'LWRIST', 'RSHOULDER', 'RELBOW', 'RWRIST'] # selected from RTM37kpts

estimate_3D_file: "/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/mesh_compare/Pose_RTM17kpts_PitchCorrect_V1/VEHS7M-Validate/X3D.npy"  # 20 fps (267300, 17, 3)

## MB mesh
estimate_mesh_17_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/mesh_compare/SMPL_RTM17kpts_V1/h36m_results.pkl'  # 17 2D kpts (277376)
# output mesh file: "/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/mesh_compare/SMPL_RTM17kpts_V1/h36m_gt.pkl"  # 20 fps 37 kpts (17336, 16, 17, 3) 17336*16=277376


## SMPLEST-X H
estimate_mesh_SMPLEST_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/mesh_compare/SMPLEST/result_VEHSR3R4/'

#estimate_mesh_SMPLEST_file: '/Users/leyangwen/Downloads/test'
