name_list: ['PELVIS',
            'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT',
            'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS',
            'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

eval_key: 'validate'

# v5-2b rtmw
GT_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/2D/Youtube_1/rtmpose_v5-2b_20fps_industry_37kpts_v2.pkl'
#GT_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/2D/Industry_Jeff/rtmpose_v5-2b_20fps_industry_37kpts_v2.pkl'
# v3v4 mb
estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-5-angleLossV2-only/v3v4/Youtube_1/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-5-angleLossV2-only/v3v4/Industry_Jeff/X3D.npy'


