name_list: ['PELVIS',
            'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT',
            'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS',
            'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/50fps/GT66kpts_v2_50fps-finetune-pitch-correct-2-angleLossV2/VEHS7M-Validate/X3D.npy'

eval_key: 'validate'

## pitch-correct
GT_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/50fps/GT2D/VEHS_6D_downsample2_keep1_pitch_correct_0.pkl'
